call npm install --save-dev backbone
call npm install --save-dev bootstrap
call npm install --save-dev browserify
call npm install --save-dev browserify-shim
call npm install --save-dev font-awesome
call npm install --save-dev jquery
call npm install --save-dev load-grunt-tasks
call npm install --save-dev marked
call npm install --save-dev matchdep
call npm install --save-dev openlayers
call npm install --save-dev proj4
call npm install --save-dev react
call npm install --save-dev react-dom
call npm install --save-dev underscore
call npm install --save-dev grunt
call npm install --save-dev grunt-autoprefixer
call npm install --save-dev grunt-babel
call npm install --save-dev grunt-browserify
call npm install --save-dev grunt-contrib-concat
call npm install --save-dev grunt-contrib-connect
call npm install --save-dev grunt-contrib-copy
call npm install --save-dev grunt-contrib-cssmin
call npm install --save-dev grunt-contrib-less
call npm install --save-dev grunt-contrib-uglify
call npm install --save-dev grunt-contrib-watch
call npm install --save-dev grunt-express
call npm install --save-dev grunt-proxy
call npm install --save-dev grunt-react
call npm install --save-dev grunt-text-replace