# Build the client
FROM registry.redhat.io/rhel9/nodejs-18 as clientBuilder
COPY /new-client/package*.json ./
USER root
RUN npm install
COPY ./new-client .
RUN npm run build --ignore-scripts

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=clientBuilder /opt/app-root/src/build .
EXPOSE 80
USER 1001
CMD ["nginx", "-g", "daemon off;"]