# Stage 1 - Building the backend
FROM registry.access.redhat.com/ubi9/nodejs-22 as backendBuilder
USER root
COPY ./apps/backend .
RUN npm ci

# Stage 2 - Building the client
FROM registry.access.redhat.com/ubi9/nodejs-22 as clientBuilder
COPY /apps/client/package*.json ./
USER root
RUN npm install
COPY ./apps/client .
RUN rm ./public/appConfig.json
RUN mv ./public/appConfig.docker.json ./public/appConfig.json
RUN npm run build --ignore-scripts

# Stage 3 - Building the admin
FROM registry.access.redhat.com/ubi9/nodejs-22 as adminBuilder
COPY /apps/admin/package*.json ./
USER root
RUN npm install
COPY ./apps/admin .
RUN rm ./public/config.json
RUN mv ./public/config.docker.json ./public/config.json 
RUN npm run build --ignore-scripts

# Stage 4 - Combine everything and fire it up
FROM registry.access.redhat.com/ubi9/nodejs-22
COPY /apps/backend/package*.json ./
USER root
RUN npm install --omit=dev --ignore-scripts
COPY --from=backendBuilder /opt/app-root/src/server ./server
COPY --from=backendBuilder /opt/app-root/src/node_modules/.prisma ./node_modules/.prisma
COPY --from=backendBuilder /opt/app-root/src/node_modules/@prisma/client ./node_modules/@prisma/client
COPY /apps/backend/.env.example ./.env
COPY /apps/backend/App_Data ./App_Data_tmp
COPY /apps/backend/static ./static
COPY --from=clientBuilder /opt/app-root/src/build ./static/client
COPY --from=adminBuilder /opt/app-root/src/build ./static/admin
RUN chown -R 1001 ./App_Data_tmp ./server ./node_modules
EXPOSE 3002
USER 1001
CMD ["npm", "run", "start"]

