FROM ubi8/nodejs-22 as backendBuilder
USER root
WORKDIR /opt/app-root/src

COPY /apps/backend/package*.json ./
RUN npm install

COPY ./apps/backend ./

RUN npm run reset:db
RUN npm run build

FROM ubi8/nodejs-22 as adminBuilder
USER root
WORKDIR /opt/app-root/src

COPY /apps/admin/package*.json ./
RUN npm install

COPY ./apps/admin ./

RUN rm ./public/config.json
RUN mv ./public/config.docker.json ./public/config.json

RUN npm run build

FROM ubi8/nodejs-22
WORKDIR /opt/app-root/src
COPY /apps/backend/package*.json ./
USER root
RUN npm install --production

RUN chown -R 1001:0 /opt/app-root/src/

USER 1001

COPY --from=backendBuilder /opt/app-root/src/dist ./
COPY /apps/backend/.env .
COPY /apps/backend/static ./static

COPY --from=adminBuilder /opt/app-root/src/dist ./static/admin

EXPOSE 3002

ENV TZ "Europe/Stockholm"
ENV PORT 3002
ENV HOSTNAME "0.0.0.0"

CMD ["npm", "start"]