export const ALLOWED_FME_PARAMETERS = [
  "CHOICE",
  "LOOKUP_CHOICE",
  "LISTBOX",
  "LOOKUP_LISTBOX",
  "RANGE_SLIDER",
  "PASSWORD",
  "TEXT",
];
export const POLLING_INTERVAL = 5000;
export const FME_FAIL_MESSAGES = ["ABORTED", "FME_FAILURE", "JOB_FAILURE"];
export const FME_SUCCESS_MESSAGES = ["SUCCESS"];
