openapi: 3.0.3
info:
  title: Hajk Backend API
  description: The Hajk backend API specification is  the authoritative specification for the API to which all Hajk backend implementations must conform.
  version: 3.0.0
servers:
  - url: /api/v3
tags:
  - name: Client-accessible
    description: Resources necessary to load a working map in client
  - name: Specification
    description: The OpenAPI specification
paths:
  /maps/{mapName}:
    get:
      tags:
        - Client-accessible
      parameters:
        - name: mapName
          in: path
          description: Name of the map to be fetched
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return the map config
        404:
          description: Requested map was not found
  /search/autocomplete:
    post:
      tags:
        - Client-accessible
      description: todo
      responses:
        200:
          description: TODO
          content: {}
      parameters:
        - in: header
          name: X-Control-Header
          description: User name that will be supplied to AD
          schema:
            type: string
          required: false
      requestBody:
        description: Json with table data
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchAutocompleteBody"
components:
  schemas:
    SearchAutocompleteBody:
      type: object
      properties:
        queryString:
          type: string
          description: "The string to search for"
          example: "stoora"
        pgTrgmSimilarityThreshold:
          type: number
          format: float
          description: "Threshold for pg_trgm similarity"
          example: 0.2
        limitPerSource:
          type: integer
          description: "Limit per source"
          example: 5
        totalLimit:
          type: integer
          description: "Total limit"
          example: 20
        sources:
          type: array
          items:
            type: object
            properties:
              table:
                type: string
                description: "Table name"
                example: "adresspunkter"
              column:
                type: string
                description: "Column name"
                example: "fastighet"
          example:
            - table: "adresspunkter"
              column: "fastighet"
            - table: "adresspunkter"
              column: "kommundel"
            - table: "adresspunkter"
              column: "beladress"
      required:
        - pgTrgmSimilarityThreshold
        - limitPerSource
        - totalLimit
        - sources
