openapi: 3.0.3
info:
  title: Hajk Backend API
  description: The Hajk backend API specification is  the authoritative specification for the API to which all Hajk backend implementations must conform.
  version: 3.0.0
servers:
  - url: /api/v3
tags:
  - name: Client-accessible
    description: Resources necessary to load a working map in client
  - name: Admin only
    description: Resources that modify the database content and required an authorized user
  - name: Specification
    description: The OpenAPI specification
paths:
  /maps:
    get:
      tags:
        - Client-accessible
      responses:
        200:
          description: Return the list of maps
        500:
          description: Internal server error
    post:
      tags:
        - Admin only
      requestBody:
        description: Json with table data
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the map
                  example: my_map
                  required: true
                options:
                  $ref: "#/components/schemas/MapConfig"
                locked:
                  type: boolean
                  description: Lock the map
                  example: false
                  required: false
      responses:
        200:
          description: Return the list of maps
        400:
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /maps/{mapName}:
    get:
      tags:
        - Client-accessible
      parameters:
        - name: mapName
          in: path
          description: Name of the map to be fetched
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return the map config
        404:
          description: Requested map was not found
    patch:
      tags:
        - Admin only
      parameters:
        - name: mapName
          in: path
          description: Name of the map to be fetched
          required: true
          schema:
            type: string
      requestBody:
        description: Json with table data
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MapConfig"
      responses:
        200:
          description: Return the map config
        400:
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - Admin only
      parameters:
        - name: mapName
          in: path
          description: Name of the map to be fetched
          required: true
          schema:
            type: string
      responses:
        204:
          description: Map deleted
        400:
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /layers:
    get:
      tags:
        - Client-accessible
      responses:
        200:
          description: Return the list of layers
        500:
          description: Internal server error
  /groups:
    get:
      tags:
        - Client-accessible
      responses:
        200:
          description: Return the list of groups
        500:
          description: Internal server error
  /groups/{groupId}:
    get:
      tags:
        - Client-accessible
      parameters:
        - name: groupId
          in: path
          description: ID of the group to be fetched
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return the group
        404:
          description: Requested group was not found
  /groups/{groupId}/maps:
    get:
      tags:
        - Client-accessible
      parameters:
        - name: groupId
          in: path
          description: ID of the group to be fetched
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return the maps that use the group
        404:
          description: Requested group was not found
  /groups/{groupId}/layers:
    get:
      tags:
        - Client-accessible
      parameters:
        - name: groupId
          in: path
          description: ID of the group to be fetched
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return the layers that belong to the group
        404:
          description: Requested group was not found
  /tools:
    get:
      tags:
        - Client-accessible
      responses:
        200:
          description: Return the list of tools
        500:
          description: Internal server error
  /tools/{toolName}/maps:
    get:
      tags:
        - Client-accessible
      parameters:
        - name: toolName
          in: path
          description: Name of the tool to be fetched
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return the maps that use the tool
        404:
          description: Requested tool was not found
  /search/autocomplete:
    post:
      tags:
        - Client-accessible
      description: Fuzzy search (for autocomplete)
      responses:
        200:
          description: List of results
          content: {}
      parameters:
        - in: header
          name: X-Control-Header
          description: User name that will be supplied to AD
          schema:
            type: string
          required: false
      requestBody:
        description: Json with table data
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchAutocompleteBody"
components:
  schemas:
    SearchAutocompleteBody:
      type: object
      properties:
        queryString:
          type: string
          description: "The string to search for"
          example: "stoora"
        pgTrgmSimilarityThreshold:
          type: number
          format: float
          description: "Threshold for pg_trgm similarity"
          example: 0.2
        limitPerSource:
          type: integer
          description: "Limit per source"
          example: 5
        totalLimit:
          type: integer
          description: "Total limit"
          example: 20
        sources:
          type: array
          items:
            type: object
            properties:
              table:
                type: string
                description: "Table name"
                example: "adresspunkter"
              column:
                type: string
                description: "Column name"
                example: "fastighet"
          example:
            - table: "adresspunkter"
              column: "fastighet"
            - table: "adresspunkter"
              column: "kommundel"
            - table: "adresspunkter"
              column: "beladress"
      required:
        - pgTrgmSimilarityThreshold
        - limitPerSource
        - totalLimit
        - sources
